// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency_keys.sql

package sqlc

import "context"

const tryCreateIdempotencyKey = `-- name: TryCreateIdempotencyKey :one
INSERT INTO idempotency_keys (key, endpoint, request_hash, response)
VALUES ($1, $2, $3, '{}'::jsonb)
ON CONFLICT (key, endpoint) DO NOTHING
RETURNING key, endpoint, request_hash, status_code, response, created_at
`

type TryCreateIdempotencyKeyParams struct {
	Key         string `json:"key"`
	Endpoint    string `json:"endpoint"`
	RequestHash string `json:"request_hash"`
}

func (q *Queries) TryCreateIdempotencyKey(ctx context.Context, arg TryCreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, tryCreateIdempotencyKey, arg.Key, arg.Endpoint, arg.RequestHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Endpoint,
		&i.RequestHash,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, endpoint, request_hash, status_code, response, created_at
FROM idempotency_keys
WHERE key = $1
  AND endpoint = $2
`

type GetIdempotencyKeyParams struct {
	Key      string `json:"key"`
	Endpoint string `json:"endpoint"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Endpoint,
		&i.RequestHash,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :one
UPDATE idempotency_keys
SET status_code = $1,
    response = $2
WHERE key = $3
  AND endpoint = $4
RETURNING key, endpoint, request_hash, status_code, response, created_at
`

type CompleteIdempotencyKeyParams struct {
	StatusCode int16  `json:"status_code"`
	Response   []byte `json:"response"`
	Key        string `json:"key"`
	Endpoint   string `json:"endpoint"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, completeIdempotencyKey, arg.StatusCode, arg.Response, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Endpoint,
		&i.RequestHash,
		&i.StatusCode,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}
