// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateMerchant(ctx context.Context, name string) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant, name)
	var i Merchant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, name, created_at FROM merchants
WHERE id = $1
`

func (q *Queries) GetMerchant(ctx context.Context, id pgtype.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listMerchants = `-- name: ListMerchants :many
SELECT id, name, created_at FROM merchants
ORDER BY created_at DESC
`

func (q *Queries) ListMerchants(ctx context.Context) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, listMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Merchant
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
