// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentMethod string

const (
	PaymentMethodCREDITCARD PaymentMethod = "CREDIT_CARD"
	PaymentMethodDEBITCARD  PaymentMethod = "DEBIT_CARD"
	PaymentMethodPIX        PaymentMethod = "PIX"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type TerminalStatus string

const (
	TerminalStatusACTIVE  TerminalStatus = "ACTIVE"
	TerminalStatusBLOCKED TerminalStatus = "BLOCKED"
)

func (e *TerminalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TerminalStatus(s)
	case string:
		*e = TerminalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TerminalStatus: %T", src)
	}
	return nil
}

type NullTerminalStatus struct {
	TerminalStatus TerminalStatus `json:"terminal_status"`
	Valid          bool           `json:"valid"` // Valid is true if TerminalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTerminalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TerminalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TerminalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTerminalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TerminalStatus), nil
}

type TransactionStatus string

const (
	TransactionStatusCREATED    TransactionStatus = "CREATED"
	TransactionStatusAUTHORIZED TransactionStatus = "AUTHORIZED"
	TransactionStatusCAPTURED   TransactionStatus = "CAPTURED"
	TransactionStatusREFUNDED   TransactionStatus = "REFUNDED"
	TransactionStatusDECLINED   TransactionStatus = "DECLINED"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type IdempotencyKey struct {
	Key         string             `json:"key"`
	Endpoint    string             `json:"endpoint"`
	RequestHash string             `json:"request_hash"`
	StatusCode  int16              `json:"status_code"`
	Response    []byte             `json:"response"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Merchant struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Terminal struct {
	ID         uuid.UUID          `json:"id"`
	Serial     string             `json:"serial"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	Status     TerminalStatus     `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID                uuid.UUID          `json:"id"`
	MerchantID        uuid.UUID          `json:"merchant_id"`
	TerminalID        uuid.UUID          `json:"terminal_id"`
	Amount            int64              `json:"amount"`
	Currency          string             `json:"currency"`
	PaymentMethod     PaymentMethod      `json:"payment_method"`
	Status            TransactionStatus  `json:"status"`
	AuthorizationCode pgtype.Text        `json:"authorization_code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type TransactionEvent struct {
	ID            uuid.UUID          `json:"id"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	Event         string             `json:"event"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
