// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terminals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTerminal = `-- name: CreateTerminal :one
INSERT INTO terminals (merchant_id, serial)
VALUES ($1, $2)
RETURNING id, serial, merchant_id, status, created_at
`

type CreateTerminalParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Serial     string    `json:"serial"`
}

func (q *Queries) CreateTerminal(ctx context.Context, arg CreateTerminalParams) (Terminal, error) {
	row := q.db.QueryRow(ctx, createTerminal, arg.MerchantID, arg.Serial)
	var i Terminal
	err := row.Scan(
		&i.ID,
		&i.Serial,
		&i.MerchantID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTerminal = `-- name: GetTerminal :one
SELECT id, serial, merchant_id, status, created_at FROM terminals
WHERE id = $1
`

func (q *Queries) GetTerminal(ctx context.Context, id uuid.UUID) (Terminal, error) {
	row := q.db.QueryRow(ctx, getTerminal, id)
	var i Terminal
	err := row.Scan(
		&i.ID,
		&i.Serial,
		&i.MerchantID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listTerminals = `-- name: ListTerminals :many
SELECT id, serial, merchant_id, status, created_at FROM terminals
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTerminals(ctx context.Context, merchantID uuid.UUID) ([]Terminal, error) {
	rows, err := q.db.Query(ctx, listTerminals, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Terminal
	for rows.Next() {
		var i Terminal
		if err := rows.Scan(
			&i.ID,
			&i.Serial,
			&i.MerchantID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTerminalStatus = `-- name: UpdateTerminalStatus :one
UPDATE terminals
SET status = $2
WHERE id = $1
RETURNING id, serial, merchant_id, status, created_at
`

type UpdateTerminalStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status TerminalStatus `json:"status"`
}

func (q *Queries) UpdateTerminalStatus(ctx context.Context, arg UpdateTerminalStatusParams) (Terminal, error) {
	row := q.db.QueryRow(ctx, updateTerminalStatus, arg.ID, arg.Status)
	var i Terminal
	err := row.Scan(
		&i.ID,
		&i.Serial,
		&i.MerchantID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
