// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeTransaction = `-- name: AuthorizeTransaction :one
UPDATE transactions SET status = 'AUTHORIZED', authorization_code = $2, updated_at = now()
WHERE id = $1 RETURNING id, merchant_id, terminal_id, amount, currency, payment_method, status, authorization_code, created_at, updated_at
`

type AuthorizeTransactionParams struct {
	ID                uuid.UUID   `json:"id"`
	AuthorizationCode pgtype.Text `json:"authorization_code"`
}

func (q *Queries) AuthorizeTransaction(ctx context.Context, arg AuthorizeTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, authorizeTransaction, arg.ID, arg.AuthorizationCode)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TerminalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.AuthorizationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const captureTransaction = `-- name: CaptureTransaction :one
UPDATE transactions SET status = 'CAPTURED', updated_at = now() WHERE id = $1 RETURNING id, merchant_id, terminal_id, amount, currency, payment_method, status, authorization_code, created_at, updated_at
`

func (q *Queries) CaptureTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, captureTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TerminalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.AuthorizationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (merchant_id, terminal_id, amount, currency, payment_method)
VALUES ($1, $2, $3, $4, $5) RETURNING id, merchant_id, terminal_id, amount, currency, payment_method, status, authorization_code, created_at, updated_at
`

type CreateTransactionParams struct {
	MerchantID    uuid.UUID     `json:"merchant_id"`
	TerminalID    uuid.UUID     `json:"terminal_id"`
	Amount        int64         `json:"amount"`
	Currency      string        `json:"currency"`
	PaymentMethod PaymentMethod `json:"payment_method"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.MerchantID,
		arg.TerminalID,
		arg.Amount,
		arg.Currency,
		arg.PaymentMethod,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TerminalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.AuthorizationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const declineTransaction = `-- name: DeclineTransaction :one
UPDATE transactions SET status = 'DECLINED', updated_at = now() WHERE id = $1 RETURNING id, merchant_id, terminal_id, amount, currency, payment_method, status, authorization_code, created_at, updated_at
`

func (q *Queries) DeclineTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, declineTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TerminalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.AuthorizationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, merchant_id, terminal_id, amount, currency, payment_method, status, authorization_code, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TerminalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.AuthorizationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionForUpdate = `-- name: GetTransactionForUpdate :one
SELECT id, merchant_id, terminal_id, amount, currency, payment_method, status, authorization_code, created_at, updated_at FROM transactions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTransactionForUpdate(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionForUpdate, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TerminalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.AuthorizationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const refundTransaction = `-- name: RefundTransaction :one
UPDATE transactions SET status = 'REFUNDED', updated_at = now() WHERE id = $1 RETURNING id, merchant_id, terminal_id, amount, currency, payment_method, status, authorization_code, created_at, updated_at
`

func (q *Queries) RefundTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, refundTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.TerminalID,
		&i.Amount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.AuthorizationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
