// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTransactionEvent = `-- name: CreateTransactionEvent :one
INSERT INTO transaction_events (transaction_id, event, payload)
VALUES ($1, $2, $3) RETURNING id, transaction_id, event, payload, created_at
`

type CreateTransactionEventParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	Event         string    `json:"event"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) CreateTransactionEvent(ctx context.Context, arg CreateTransactionEventParams) (TransactionEvent, error) {
	row := q.db.QueryRow(ctx, createTransactionEvent, arg.TransactionID, arg.Event, arg.Payload)
	var i TransactionEvent
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Event,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionEvent = `-- name: ListTransactionEvent :many
SELECT id, transaction_id, event, payload, created_at FROM transaction_events WHERE transaction_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTransactionEvent(ctx context.Context, transactionID uuid.UUID) ([]TransactionEvent, error) {
	rows, err := q.db.Query(ctx, listTransactionEvent, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionEvent
	for rows.Next() {
		var i TransactionEvent
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Event,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
